# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IGListKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IGListKitTest
  pod 'IGListKit', '~> 4.0.0'

end
